### ISSUE TITLE
Field References

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/navdevitpro-content-pr#2167]
Is there some reason that references to fields on NAV pages appear like this  ($ T_5305_1 User ID $)  in this doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaeeb698-36bc-b3eb-38e2-ac69785f7261
* Version Independent ID: 48a2ed08-20cb-ff38-dc39-4aa167479d8f
* Content: [Walkthrough: Setting Up Outlook Synchronization - Dynamics NAV](https://docs.microsoft.com/en-us/dynamics-nav/walkthrough--setting-up-outlook-synchronization)
* Content Source: [dynamics-nav/Walkthrough--Setting-Up-Outlook-Synchronization.md](https://github.com/MicrosoftDocs/navdevitpro-content-pr/blob/live/dynamics-nav/Walkthrough--Setting-Up-Outlook-Synchronization.md)
* Product: **dynamics-nav-2018**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello David,
Yes, it's because the content was not processed with a now deprecated tool when it was migrated to GitHub. The deprecated tool replaced such codes with the actual caption, derived from the user face strings at build time. We no longer support that process.

**Comment by buzzwick** [comment]
Eva,
Okay, so...does that mean that references to fields will show going forward as the actual caption, or that you no longer support the process of replacing such codes with the actual captions? Are you supporting a new process that does do these replacements?

**Comment by edupont04** [comment]
Hello again,
I mean we "no longer support the process of replacing such codes with the actual captions". When we migrated this particular article to MarkDown format in GitHub, we forgot (it would seem) that it contained these codes. You can compare to the NAV 2016 docs that were processed in a different way: [https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/dd338966(v=nav.90)](https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/dd338966(v=nav.90)), for example.

I've closed the Issue because it's not a priority for us to clean up the codes - the walkthrough works, you can follow the steps, and the captions just happen to include codes for which table and field they come from.

**Comment by buzzwick** [comment]
Got it. I can see how this would not merit the expenditure of a lot of precious effort. I will deal!
Thanks,

David
